/* v50.46 collection workflow; undo history and image bytes stay device-local. */
const workflowV546={sessions:new Map(),suspended:false,filter:null,urls:[],lastDetail:null};
function trackedV546(){return {collection:structuredClone(state.collection||[]),wishlist:structuredClone(state.wishlist||[]),modules:structuredClone(state.modules||{}),instances:structuredClone(state.meta?.instanceModulesV536||{})}}
function baselineV546(){workflowV546.sessions.set(ownerV544(),{last:trackedV546(),undo:[]})}
const persistWorkflowBaseV546=persist;
persist=function(){
 if(!cloudApplyingV3&&!workflowV546.suspended){
  let s=workflowV546.sessions.get(ownerV544());if(!s){baselineV546();s=workflowV546.sessions.get(ownerV544())}
  const current=trackedV546();
  if(JSON.stringify(current)!==JSON.stringify(s.last)){
   s.undo.unshift(s.last);s.undo=s.undo.slice(0,10);
   const old=new Map(s.last.collection.map(x=>[String(x.setNumber),JSON.stringify(x)]));const assigned=(modules,n)=>Object.keys(modules||{}).filter(m=>modules[m].map(String).includes(String(n))).sort().join(',');
   for(const x of state.collection||[])if(old.get(String(x.setNumber))!==JSON.stringify(x)||assigned(s.last.modules,x.setNumber)!==assigned(current.modules,x.setNumber))x.updatedAtV546=new Date().toISOString();
   s.last=trackedV546();
  }
 }
 const r=persistWorkflowBaseV546();renderUndoV546();return r;
};
function undoV546(){
 const s=workflowV546.sessions.get(ownerV544());if(!s?.undo.length)return;
 const previous=s.undo.shift(),currentReceipts=new Map(state.collection.map(x=>[String(x.setNumber),x.receiptsV545]));
 workflowV546.suspended=true;
 try{state.collection=structuredClone(previous.collection);for(const x of state.collection)if(currentReceipts.has(String(x.setNumber)))x.receiptsV545=currentReceipts.get(String(x.setNumber));state.wishlist=structuredClone(previous.wishlist);state.modules=structuredClone(previous.modules);state.meta.instanceModulesV536=structuredClone(previous.instances);s.last=trackedV546();persist();refresh()}finally{workflowV546.suspended=false}
}
function renderUndoV546(){let b=$('undoV546');if(!b){const host=document.querySelector('.headActions');if(!host)return;b=document.createElement('button');b.id='undoV546';b.className='btn secondary';b.textContent='↶ Rückgängig';b.onclick=undoV546;host.appendChild(b)}b.disabled=!workflowV546.sessions.get(ownerV544())?.undo.length;b.title='Letzte Sammlungsänderung dieser Sitzung rückgängig machen'}
function matchesFilterV546(x,f){
 if(f.query&&!nV3([x.setNumber,x.name,x.category,x.storage,x.cityArea].join(' ')).includes(nV3(f.query)))return false;
 if(f.area&&x.cityArea!==f.area)return false;
 if(f.kind==='sealed'&&x.condition!=='Neu / OVP')return false;
 if(f.kind==='nobox'&&!(x.box==='Nein'||(x.exemplars?.length&&x.exemplars.every(e=>e.box==='Nein'))))return false;
 if(f.kind==='sale'&&!x.forSaleV546)return false;
 return true;
}
const filteredWorkflowBaseV546=filteredV3;filteredV3=function(){const rows=filteredWorkflowBaseV546();return workflowV546.filter?rows.filter(x=>matchesFilterV546(x,workflowV546.filter)):rows};
function renderSavedFiltersV546(){const box=cardV544('collection','savedFiltersV546','Eigene Ansichten');if(!box||box.dataset.owner===ownerV544())return;box.dataset.owner=ownerV544();box.innerHTML='<h2>Eigene Ansichten</h2><div class="actions"><select id="savedSelectV546" aria-label="Gespeicherte Ansicht"></select><select id="filterKindV546" aria-label="Zusatzfilter"><option value="">Alle Zustände</option><option value="sealed">Neu / OVP</option><option value="nobox">Ohne Karton (bestätigt)</option><option value="sale">Zum Verkauf markiert</option></select><input id="filterNameV546" maxlength="50" placeholder="Name der Ansicht"><button class="btn secondary" id="saveFilterV546">Ansicht speichern</button><button class="btn secondary" id="clearFilterV546">Filter löschen</button><button class="btn secondary" id="deleteFilterV546">Ansicht entfernen</button></div>';
 const paint=()=>{$('savedSelectV546').innerHTML='<option value="">Gespeicherte Ansicht wählen</option>'+(state.meta.savedFiltersV546||[]).map(f=>'<option value="'+esc(f.id)+'">'+esc(f.name)+'</option>').join('')};paint();
 $('filterKindV546').onchange=()=>{workflowV546.filter={kind:$('filterKindV546').value};renderCollection()};
 $('saveFilterV546').onclick=()=>{const name=$('filterNameV546').value.trim();if(!name)return;state.meta.savedFiltersV546=state.meta.savedFiltersV546||[];if(state.meta.savedFiltersV546.length>=20)return alert('Bitte zuerst eine ältere Ansicht entfernen.');state.meta.savedFiltersV546.push({id:crypto.randomUUID(),name,query:$('search')?.value||'',area:$('areaFilter')?.value||'',kind:$('filterKindV546').value});persist();paint()};
 $('savedSelectV546').onchange=()=>{const f=state.meta.savedFiltersV546?.find(f=>f.id===$('savedSelectV546').value);workflowV546.filter=f||null;if($('search'))$('search').value=f?.query||'';if($('areaFilter'))$('areaFilter').value=f?.area||'';$('filterKindV546').value=f?.kind||'';renderCollection()};
 $('clearFilterV546').onclick=()=>{workflowV546.filter=null;if($('search'))$('search').value='';if($('areaFilter'))$('areaFilter').value='';$('filterKindV546').value='';$('savedSelectV546').value='';renderCollection()};
 $('deleteFilterV546').onclick=()=>{const id=$('savedSelectV546').value;if(!id)return;state.meta.savedFiltersV546=(state.meta.savedFiltersV546||[]).filter(f=>f.id!==id);workflowV546.filter=null;persist();paint();renderCollection()};
}
function renderRecentV546(){const box=cardV544('home','recentV546','Zuletzt bearbeitet');if(!box)return;const rows=state.collection.filter(x=>x.updatedAtV546).sort((a,b)=>Date.parse(b.updatedAtV546)-Date.parse(a.updatedAtV546)).slice(0,6);box.innerHTML='<h2>Zuletzt bearbeitet</h2>'+(rows.length?rows.map(x=>'<p><button class="linkbtn" data-recent-v546="'+esc(x.setNumber)+'">'+esc(x.setNumber+' · '+x.name)+'</button><br><small>'+esc(new Date(x.updatedAtV546).toLocaleString('de-DE'))+'</small></p>').join(''):'<p class="hint">Deine nächsten Änderungen erscheinen hier.</p>');box.querySelectorAll('[data-recent-v546]').forEach(b=>b.onclick=()=>showDetailV3(b.dataset.recentV546))}
function priorityV546(p){const n=Number(p);return Number.isFinite(n)&&n>0?n:({a:1,b:2,c:3,hoch:1,mittel:2,niedrig:3}[String(p||'').toLowerCase()]||99)}
function budgetSummaryV546(budget){const rows=state.wishlist.map(w=>({w,cost:Number(w.offer)>0&&w.offerShippingV545!==undefined&&w.offerShippingV545!==''?Number(w.offer)+Number(w.offerShippingV545):0})).filter(r=>r.cost>0&&Number.isFinite(r.cost)).sort((a,b)=>priorityV546(a.w.priority)-priorityV546(b.w.priority)||a.cost-b.cost);let remaining=budget;return rows.map(r=>{const fit=r.cost<=remaining;if(fit)remaining-=r.cost;return {...r,fit,remaining}})}
function renderBudgetV546(){const box=cardV544('wishlist','budgetV546','Sammlungsziel & Monatsbudget');if(!box||box.dataset.owner===ownerV544())return;box.dataset.owner=ownerV544();box.innerHTML='<h2>Sammlungsziel & Monatsbudget</h2><div class="form"><label>Dein Ziel<input id="goalV546" maxlength="100" placeholder="Zum Beispiel: Weihnachtsdorf vervollständigen" value="'+esc(state.meta.goalV546||'')+'"></label><label>Verfügbares Budget für diesen Monat (€)<input id="budgetInputV546" type="number" min="0" step="0.01" value="'+esc(state.meta.budgetV546??'')+'"></label></div><button class="btn secondary" id="budgetSaveV546">Speichern & vergleichen</button><div id="budgetResultsV546"></div><p class="hint">Plant Wünsche mit bekannten Angebotspreisen und Versand in Prioritätsreihenfolge. Dies ist ein Planungstopf, keine automatische Ausgabenbuchhaltung.</p>';
 const paint=()=>{const rows=budgetSummaryV546(Number(state.meta.budgetV546||0));$('budgetResultsV546').innerHTML=rows.length?rows.map(r=>'<p>'+esc(r.w.setNumber+' · '+r.w.name)+' - '+euro(r.cost)+' · '+(r.fit?'passt in den Planungstopf':'Budget reicht nicht')+'</p>').join(''):'<p>Bitte Angebote einschließlich Versand erfassen.</p>'};paint();$('budgetSaveV546').onclick=()=>{const b=Number($('budgetInputV546').value);if(!Number.isFinite(b)||b<0)return;state.meta.budgetV546=b;state.meta.goalV546=$('goalV546').value.trim();persist();paint()};
}
function pdfAuditV546(snapshot=state){return snapshot.collection.map(x=>({x,issues:[!Number(x.purchasePrice)&&'Kaufpreis fehlt',(!x.condition||x.condition==='Unbekannt')&&'Zustand unbekannt',!(x.receiptsV545||[]).length&&'Kein Beleg erfasst'].filter(Boolean)})).filter(r=>r.issues.length)}
function renderPdfAuditV546(){const host=$('pdfOptionsV545');if(!host)return;let box=$('pdfAuditV546');if(!box){box=document.createElement('details');box.id='pdfAuditV546';host.prepend(box)}const rows=pdfAuditV546();box.innerHTML='<summary>Datenprüfung: '+rows.length+' Sets mit fehlenden Angaben</summary><p class="hint">Fehlende Angaben werden in der PDF als unbekannt ausgewiesen. Belegbilder müssen auf diesem Gerät verfügbar sein.</p>'+rows.slice(0,50).map(r=>'<p><button class="linkbtn" data-audit-v546="'+esc(r.x.setNumber)+'">'+esc(r.x.setNumber+' · '+r.x.name)+'</button><br>'+esc(r.issues.join(' · '))+'</p>').join('')+(rows.length>50?'<p>Weitere '+(rows.length-50)+' Sets mit fehlenden Angaben.</p>':'');box.querySelectorAll('[data-audit-v546]').forEach(b=>b.onclick=()=>showDetailV3(b.dataset.auditV546))}
async function addExemplarPhotoV546(n,index,file){if(!file)return;const user=ownerV544(),x=state.collection.find(x=>String(x.setNumber)===String(n)),e=x?.exemplars?.[index];if(!e)return;if(!['image/jpeg','image/png'].includes(file.type)||file.size>5*1024*1024)return alert('Bitte JPG/PNG bis 5 MB wählen.');try{const id=crypto.randomUUID();await receiptActionV545('put',user+':photo:'+id,file);if(ownerV544()!==user)return;e.photosV546=e.photosV546||[];e.photosV546.push({id,name:file.name});persist();showDetailV3(n)}catch{alert('Foto konnte nicht gespeichert werden.')}}
async function showExemplarPhotosV546(box,n){const user=ownerV544(),x=state.collection.find(x=>String(x.setNumber)===String(n));for(const [i,e] of (x?.exemplars||[]).entries())for(const p of e.photosV546||[]){const blob=await receiptActionV545('get',user+':photo:'+p.id).catch(()=>null);if(ownerV544()!==user||!box.isConnected)return;const host=box.querySelector('[data-photo-list="'+i+'"]');if(blob&&host){const url=URL.createObjectURL(blob);workflowV546.urls.push(url);const img=document.createElement('img');img.src=url;img.alt=p.name;img.className='exPhotoV546';host.appendChild(img)}}}
function renderDetailWorkflowV546(n){workflowV546.urls.forEach(u=>URL.revokeObjectURL(u));workflowV546.urls=[];const root=$('detailContent'),x=state.collection.find(x=>String(x.setNumber)===String(n));if(!root||!x)return;root.querySelector('#detailWorkflowV546')?.remove();ensureExemplarIdsV536();const box=document.createElement('div');box.id='detailWorkflowV546';box.className='card wide';box.innerHTML='<h3>Baufortschritt & Exemplarfotos</h3><div class="form"><label>Bauabschnitt / Beutel<input id="buildStageV546" maxlength="100" value="'+esc(x.buildProgressV546?.stage||'')+'"></label><label>Anleitungsseite<input id="buildPageV546" type="number" min="1" value="'+esc(x.buildProgressV546?.page||'')+'"></label><label><input id="forSaleV546" type="checkbox" '+(x.forSaleV546?'checked':'')+'> Zum Verkauf vormerken</label></div><button class="btn secondary" id="progressSaveV546">Fortschritt speichern</button><p class="hint">Exemplarfotos sind auf diesem Gerät gespeichert. In der PDF werden verfügbare Fotos aufgenommen, wenn Setfotos eingeschaltet sind.</p>'+x.exemplars.map((e,i)=>'<details><summary>Exemplar '+(i+1)+' - '+esc(e.condition||x.condition||'Unbekannt')+'</summary><label class="btn secondary">Foto hinzufügen<input type="file" accept="image/jpeg,image/png" data-ex-photo="'+i+'" hidden></label><div data-photo-list="'+i+'"></div></details>').join('');root.appendChild(box);$('progressSaveV546').onclick=()=>{const page=Number($('buildPageV546').value);x.buildProgressV546={stage:$('buildStageV546').value.trim(),page:Number.isInteger(page)&&page>0?page:null,updatedAt:new Date().toISOString()};x.forSaleV546=$('forSaleV546').checked;persist();$('progressSaveV546').textContent='Gespeichert'};box.querySelectorAll('[data-ex-photo]').forEach(el=>el.onchange=()=>addExemplarPhotoV546(n,Number(el.dataset.exPhoto),el.files[0]));showExemplarPhotosV546(box,n)}
const detailWorkflowBaseV546=detailTabsV38;detailTabsV38=function(n){const r=detailWorkflowBaseV546(n);renderDetailWorkflowV546(n);return r};
function renderWorkflowV546(){renderUndoV546();if($('home')?.classList.contains('active'))renderRecentV546();if($('collection')?.classList.contains('active')){renderSavedFiltersV546();renderPdfAuditV546()}if($('wishlist')?.classList.contains('active'))renderBudgetV546()}
const refreshWorkflowBaseV546=refresh;refresh=function(){const r=refreshWorkflowBaseV546();renderWorkflowV546();return r};
const switchWorkflowBaseV546=switchTab;switchTab=function(id){const r=switchWorkflowBaseV546(id);renderWorkflowV546();return r};
const sessionWorkflowBaseV546=cloudSessionV3;cloudSessionV3=async function(s){workflowV546.filter=null;workflowV546.suspended=true;try{return await sessionWorkflowBaseV546(s)}finally{baselineV546();workflowV546.suspended=false;renderWorkflowV546()}};
const exportWorkflowBaseV546=exportPortfolioV545;exportPortfolioV545=async function(){renderPdfAuditV546();return exportWorkflowBaseV546()};
setTimeout(()=>{baselineV546();renderWorkflowV546();if($('pdfCreateV545'))$('pdfCreateV545').onclick=exportPortfolioV545;if($('appVersion'))$('appVersion').textContent='v50.47'},600);
